#!/bin/bash
# regex to validate in commit msg
shopt -s nocasematch
commit_regex="(\[[A-Z]{2,5}-[0-9]+\]|merge)"
commit_msg=$(cat "${1:?Missing commit message file}")
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue '[WAP-1111]' or 'Merge'"

if ! [[ $commit_msg =~ $commit_regex ]]; then
    echo $error_msg >&2
    exit 1
fi
