#
# Okta Webhook POC
#
service: okta-webhook

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: dev
  deploymentBucket: s37-dev-lambda
  deploymentPrefix: serverless # S3://s37-dev-lambda/serverless/<service name>/<stage>

plugins:
  - serverless-pseudo-parameters
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  TokenHandler:
    handler: lambda-index.handler
    events:
      - http:
          method: post
          path: /v1/token
